---
- name: Pull and run Docker image
  hosts: host_machine
  become: yes

  tasks:
    - name: Pull Docker image
      docker_image:
        name: mbaapoh/maviance-devops-app:1.0.0
        source: pull

    - name: Run Docker container
      docker_container:
        name: deploy_container
        image: mbaapoh/maviance-devops-app:1.0.0
        detach: yes
        restart_policy: always

    - name: Get Docker container info
      docker_container_info:
        name: deploy_container
      register: container_info

    - name: Print container logs
      debug:
        var: container_info.logs
