- name: Pull and run Docker image
  hosts: jenkins_container
  become: yes

  tasks:
    - name: Pull Docker image
      docker_image:
        name: mbaapoh/maviance-devops-app:1.0.0
        source: pull
